modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="agentchat.png"
credits="lumoren"
authors="lumoren"
configScreen="com.lumoren.agentchat.ui.ConfigScreen"
description='''
An AI chat assistant mod for Minecraft (NeoForge ${minecraft_version})
'''

[[dependencies.agentchat]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.agentchat]]
modId="jei"
mandatory=false
ordering="AFTER"
