package com.lumoren.agentchat.model;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.time.Instant;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * 项目模型单元测试。
 * <p>
 * 验证 Project、Task、ItemRequirement、枚举等数据模型的正确性。
 * 这些测试不依赖 Minecraft 运行时。
 */
class ProjectTest {

    /**
     * Gson 实例，注册了 {@link Instant} 的 TypeAdapter。
     * Instant 序列化为 ISO-8601 字符串，反序列化亦然。
     */
    private final Gson gson = new GsonBuilder()
            .registerTypeAdapter(Instant.class, new TypeAdapter<Instant>() {
                @Override
                public void write(JsonWriter out, Instant value) throws IOException {
                    out.value(value.toString());
                }

                @Override
                public Instant read(JsonReader in) throws IOException {
                    return Instant.parse(in.nextString());
                }
            })
            .create();

    // ========== 枚举基础测试 ==========

    @Test
    void projectStatus_hasAllExpectedValues() {
        ProjectStatus[] values = ProjectStatus.values();
        assertEquals(4, values.length);
        assertEquals(ProjectStatus.CREATED, ProjectStatus.valueOf("CREATED"));
        assertEquals(ProjectStatus.IN_PROGRESS, ProjectStatus.valueOf("IN_PROGRESS"));
        assertEquals(ProjectStatus.COMPLETED, ProjectStatus.valueOf("COMPLETED"));
        assertEquals(ProjectStatus.ARCHIVED, ProjectStatus.valueOf("ARCHIVED"));
    }

    @Test
    void taskStatus_hasAllExpectedValues() {
        TaskStatus[] values = TaskStatus.values();
        assertEquals(4, values.length);
        assertEquals(TaskStatus.PENDING, TaskStatus.valueOf("PENDING"));
        assertEquals(TaskStatus.IN_PROGRESS, TaskStatus.valueOf("IN_PROGRESS"));
        assertEquals(TaskStatus.DONE, TaskStatus.valueOf("DONE"));
        assertEquals(TaskStatus.BLOCKED, TaskStatus.valueOf("BLOCKED"));
    }

    @Test
    void taskType_hasAllExpectedValues() {
        TaskType[] values = TaskType.values();
        assertEquals(6, values.length);
        assertEquals(TaskType.CRAFT, TaskType.valueOf("CRAFT"));
        assertEquals(TaskType.GATHER, TaskType.valueOf("GATHER"));
        assertEquals(TaskType.GO_TO, TaskType.valueOf("GO_TO"));
        assertEquals(TaskType.USE, TaskType.valueOf("USE"));
        assertEquals(TaskType.KILL, TaskType.valueOf("KILL"));
        assertEquals(TaskType.PLAN, TaskType.valueOf("PLAN"));
    }

    // ========== ItemRequirement ==========

    @Test
    void itemRequirement_createdWithCorrectFields() {
        ItemRequirement req = new ItemRequirement("minecraft:diamond", 3, 1);

        assertEquals("minecraft:diamond", req.itemId());
        assertEquals(3, req.needed());
        assertEquals(1, req.owned());
    }

    // ========== Task ==========

    @Test
    void task_autoGeneratesIdWhenNull() {
        Task task = new Task(null, "采掘钻石", TaskType.GATHER, TaskStatus.PENDING,
                List.of(new ItemRequirement("minecraft:diamond", 3, 0)), null);

        assertNotNull(task.id());
        assertTrue(task.id().length() > 0);
    }

    @Test
    void task_usesProvidedId() {
        Task task = new Task("custom-id", "合成钻石剑", TaskType.CRAFT, TaskStatus.PENDING, List.of(), null);

        assertEquals("custom-id", task.id());
    }

    @Test
    void task_factoryMethodCreatesWithDefaults() {
        Task task = Task.of("前往下界", TaskType.GO_TO, List.of());

        assertNotNull(task.id());
        assertEquals("前往下界", task.description());
        assertEquals(TaskType.GO_TO, task.type());
        assertEquals(TaskStatus.PENDING, task.status());
        assertTrue(task.requiredItems().isEmpty());
        assertNull(task.note());
    }

    @Test
    void task_immutableStatusSequence() {
        // Task is a record — each status is a different instance
        Task pending = new Task("id-1", "收集木头", TaskType.GATHER, TaskStatus.PENDING, List.of(), null);
        Task inProgress = new Task("id-1", "收集木头", TaskType.GATHER, TaskStatus.IN_PROGRESS, List.of(), null);
        Task done = new Task("id-1", "收集木头", TaskType.GATHER, TaskStatus.DONE, List.of(), null);
        Task blocked = new Task("id-1", "收集木头", TaskType.GATHER, TaskStatus.BLOCKED, List.of(), null);

        assertEquals(TaskStatus.PENDING, pending.status());
        assertEquals(TaskStatus.IN_PROGRESS, inProgress.status());
        assertEquals(TaskStatus.DONE, done.status());
        assertEquals(TaskStatus.BLOCKED, blocked.status());
    }

    // ========== Project ==========

    @Test
    void project_createsWithAutoGeneratedId() {
        Project project = new Project("测试项目");

        assertNotNull(project.getId());
        assertEquals("测试项目", project.getName());
        assertEquals(ProjectStatus.CREATED, project.getStatus());
        assertTrue(project.getTasks().isEmpty());
        assertNotNull(project.getCreatedAt());
        assertNotNull(project.getUpdatedAt());
    }

    @Test
    void project_addTask() {
        Project project = new Project("测试项目");
        Task task = Task.of("收集3个钻石", TaskType.GATHER,
                List.of(new ItemRequirement("minecraft:diamond", 3, 0)));

        project.addTask(task);

        assertEquals(1, project.getTasks().size());
        assertEquals("收集3个钻石", project.getTasks().getFirst().description());
    }

    @Test
    void project_getTasksReturnsImmutable() {
        Project project = new Project("测试项目");
        project.addTask(Task.of("任务1", TaskType.PLAN, List.of()));

        List<Task> tasks = project.getTasks();
        assertThrows(UnsupportedOperationException.class, () -> tasks.add(Task.of("不应添加", TaskType.PLAN, List.of())));
    }

    @Test
    void project_setTasks() {
        Project project = new Project("测试项目");
        List<Task> newTasks = List.of(
                Task.of("任务1", TaskType.CRAFT, List.of()),
                Task.of("任务2", TaskType.GATHER, List.of())
        );

        project.setTasks(newTasks);

        assertEquals(2, project.getTasks().size());
    }

    @Test
    void project_setTasksReplacesExisting() {
        Project project = new Project("测试项目");
        project.addTask(Task.of("旧任务", TaskType.PLAN, List.of()));

        project.setTasks(List.of(Task.of("新任务", TaskType.GO_TO, List.of())));

        assertEquals(1, project.getTasks().size());
        assertEquals("新任务", project.getTasks().getFirst().description());
    }

    @Test
    void project_emptyTasksList() {
        Project project = new Project("空项目");

        assertTrue(project.getTasks().isEmpty());
        assertEquals(0, project.getTasks().size());
    }

    @Test
    void project_setStatus() {
        Project project = new Project("测试项目");

        project.setStatus(ProjectStatus.IN_PROGRESS);
        assertEquals(ProjectStatus.IN_PROGRESS, project.getStatus());

        project.setStatus(ProjectStatus.COMPLETED);
        assertEquals(ProjectStatus.COMPLETED, project.getStatus());

        project.setStatus(ProjectStatus.ARCHIVED);
        assertEquals(ProjectStatus.ARCHIVED, project.getStatus());
    }

    @Test
    void project_setStatusUpdatesTimestamp() {
        Project project = new Project("测试项目");
        Instant beforeUpdate = project.getUpdatedAt();

        // 确保时间流逝（至少 1ms）
        try {
            Thread.sleep(5);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        project.setStatus(ProjectStatus.IN_PROGRESS);

        assertTrue(project.getUpdatedAt().isAfter(beforeUpdate));
    }

    @Test
    void project_setName() {
        Project project = new Project("旧名称");
        project.setName("新名称");
        assertEquals("新名称", project.getName());
    }

    @Test
    void project_setId() {
        Project project = new Project("测试");
        project.setId("custom-id-123");
        assertEquals("custom-id-123", project.getId());
    }

    @Test
    void project_clearTasks() {
        Project project = new Project("测试项目");
        project.addTask(Task.of("任务1", TaskType.PLAN, List.of()));
        project.addTask(Task.of("任务2", TaskType.CRAFT, List.of()));

        project.clearTasks();

        assertTrue(project.getTasks().isEmpty());
    }

    // ========== 序列化反序列化 ==========

    @Test
    void project_serializationRoundTrip() {
        List<ItemRequirement> items = List.of(
                new ItemRequirement("minecraft:diamond", 3, 0),
                new ItemRequirement("minecraft:stick", 2, 0)
        );
        List<Task> tasks = List.of(
                new Task("task-1", "收集钻石", TaskType.GATHER, TaskStatus.PENDING, items, "注意安全"),
                new Task("task-2", "合成钻石剑", TaskType.CRAFT, TaskStatus.PENDING, List.of(), null)
        );
        Project original = new Project("project-1", "钻石剑计划", tasks, ProjectStatus.CREATED,
                Instant.parse("2025-01-01T00:00:00Z"), Instant.parse("2025-01-01T00:00:00Z"));

        String json = gson.toJson(original);
        Project restored = gson.fromJson(json, Project.class);

        assertEquals(original.getId(), restored.getId());
        assertEquals(original.getName(), restored.getName());
        assertEquals(original.getStatus(), restored.getStatus());
        assertEquals(original.getCreatedAt(), restored.getCreatedAt());
        assertEquals(original.getUpdatedAt(), restored.getUpdatedAt());
        assertEquals(original.getTasks().size(), restored.getTasks().size());

        // 验证第一个任务
        Task originalTask = original.getTasks().get(0);
        Task restoredTask = restored.getTasks().get(0);
        assertEquals(originalTask.id(), restoredTask.id());
        assertEquals(originalTask.description(), restoredTask.description());
        assertEquals(originalTask.type(), restoredTask.type());
        assertEquals(originalTask.status(), restoredTask.status());
        assertEquals(originalTask.note(), restoredTask.note());

        // 验证物品需求
        assertEquals(originalTask.requiredItems().size(), restoredTask.requiredItems().size());
        assertEquals(
                originalTask.requiredItems().get(0).itemId(),
                restoredTask.requiredItems().get(0).itemId()
        );
        assertEquals(
                originalTask.requiredItems().get(0).needed(),
                restoredTask.requiredItems().get(0).needed()
        );
        assertEquals(
                originalTask.requiredItems().get(0).owned(),
                restoredTask.requiredItems().get(0).owned()
        );
    }

    @Test
    void project_emptyTasksSerializationRoundTrip() {
        Project original = new Project("empty-1", "空项目", List.of(), ProjectStatus.CREATED,
                Instant.parse("2025-06-01T00:00:00Z"), Instant.parse("2025-06-01T00:00:00Z"));

        String json = gson.toJson(original);
        Project restored = gson.fromJson(json, Project.class);

        assertEquals(original.getId(), restored.getId());
        assertEquals(original.getName(), restored.getName());
        assertTrue(restored.getTasks().isEmpty());
    }

    @Test
    void itemRequirement_serializationRoundTrip() {
        ItemRequirement original = new ItemRequirement("minecraft:iron_ingot", 5, 2);

        String json = gson.toJson(original);
        ItemRequirement restored = gson.fromJson(json, ItemRequirement.class);

        assertEquals(original.itemId(), restored.itemId());
        assertEquals(original.needed(), restored.needed());
        assertEquals(original.owned(), restored.owned());
    }

    @Test
    void task_serializationRoundTrip() {
        List<ItemRequirement> items = List.of(new ItemRequirement("minecraft:iron_ingot", 5, 0));
        Task original = new Task("task-serial-1", "合成铁剑", TaskType.CRAFT, TaskStatus.PENDING, items, "测试备注");

        String json = gson.toJson(original);
        Task restored = gson.fromJson(json, Task.class);

        assertEquals(original.id(), restored.id());
        assertEquals(original.description(), restored.description());
        assertEquals(original.type(), restored.type());
        assertEquals(original.status(), restored.status());
        assertEquals(original.note(), restored.note());
        assertEquals(original.requiredItems().size(), restored.requiredItems().size());
    }
}
